export const categories = [
  { id: "1", name: "Burgers", icon: "🍔" },
  { id: "2", name: "Pizza", icon: "🍕" },
  { id: "3", name: "Chicken", icon: "🍗" },
  { id: "4", name: "Shawarma", icon: "🌯" },
  { id: "5", name: "Drinks", icon: "🥤" },
  { id: "6", name: "Fries", icon: "🍟" },
  { id: "7", name: "Waffle", icon: "🧇" },
  { id: "8", name: "Dessert", icon: "🍰" },
];

export const menuItems = [
  {
    id: "1",
    name: "Classic Smash Burger",
    categoryId: "1",
    description: "Double beef patty, melted cheddar, caramelized onions, house sauce on a toasted brioche bun.",
    price: 12.99,
    offerPrice: 10.99,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800&h=600",
    isVeg: false,
    isBestSeller: true,
    isNew: false,
    isPopular: true,
    spicyLevel: 1,
    isAvailable: true,
    prepTime: "15 min",
  },
  {
    id: "2",
    name: "Spicy Zinger Wrap",
    categoryId: "4",
    description: "Crispy chicken strips, jalapenos, fresh lettuce, and spicy mayo wrapped in a toasted tortilla.",
    price: 8.99,
    offerPrice: null,
    image: "https://images.unsplash.com/photo-1626804475297-41609ea0aa4d?auto=format&fit=crop&q=80&w=800&h=600",
    isVeg: false,
    isBestSeller: false,
    isNew: true,
    isPopular: true,
    spicyLevel: 3,
    isAvailable: true,
    prepTime: "10 min",
  },
  {
    id: "3",
    name: "Loaded Cheese Fries",
    categoryId: "6",
    description: "Crispy golden fries topped with melted cheddar cheese, jalapenos, and our signature secret sauce.",
    price: 6.49,
    offerPrice: 5.49,
    image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&q=80&w=800&h=600",
    isVeg: true,
    isBestSeller: true,
    isNew: false,
    isPopular: false,
    spicyLevel: 2,
    isAvailable: true,
    prepTime: "8 min",
  },
  {
    id: "4",
    name: "Margherita Pizza",
    categoryId: "2",
    description: "Fresh tomato sauce, mozzarella cheese, and fragrant basil leaves on a thin crust.",
    price: 14.99,
    offerPrice: null,
    image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?auto=format&fit=crop&q=80&w=800&h=600",
    isVeg: true,
    isBestSeller: false,
    isNew: false,
    isPopular: true,
    spicyLevel: 0,
    isAvailable: true,
    prepTime: "20 min",
  },
  {
    id: "5",
    name: "Oreo Waffle Delight",
    categoryId: "7",
    description: "Warm waffle topped with crushed Oreos, vanilla ice cream, and chocolate syrup.",
    price: 7.99,
    offerPrice: null,
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f11cb?auto=format&fit=crop&q=80&w=800&h=600",
    isVeg: true,
    isBestSeller: true,
    isNew: true,
    isPopular: false,
    spicyLevel: 0,
    isAvailable: true,
    prepTime: "12 min",
  },
];
